name: Build and Push API Docker Image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  TARGET_OWNER: santoae_sonaemc
  IMAGE_TAG: latest
  IMAGE_NAME: perf-test-platform  # <-- Set your image name here (matches subdir in Dockerfiles/)
  CONTEXT: Dockerfiles/perf-test-platform  # <-- Set your build context here
  DOCKERFILE: Dockerfiles/perf-test-platform/Dockerfile  # <-- Set your Dockerfile path here

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.TARGET_OWNER }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        run: |
          set -e
          echo "Building $IMAGE_NAME from $DOCKERFILE"
          docker buildx build \
            --push \
            --file "$DOCKERFILE" \
            --tag "$REGISTRY/$TARGET_OWNER/$IMAGE_NAME:$IMAGE_TAG" \
            "$CONTEXT"
          echo "Built and pushed: $REGISTRY/$TARGET_OWNER/$IMAGE_NAME:$IMAGE_TAG"

      - name: Output image details
        run: |
          echo "Image: ${{ env.REGISTRY }}/${{ env.TARGET_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"