name: LAC.0005-TEST.0001-Load-Test-multi-server

on:
  workflow_dispatch

jobs:
  performance-test:
    runs-on: self-hosted
    timeout-minutes: 60  # Set timeout to 60 minutes (1 hour)

    steps:
    - name: Defining test specific environment variables
      run: |
      
        # Test specific environment variables

        echo "LAC_ID=LAC.0005" >> $GITHUB_ENV
        echo "TEST_ID=TEST.0001" >> $GITHUB_ENV

    - name: Running test  
      run: |
        echo "Running performance test ${{ env.TEST_ID }} on LAC ${{ env.LAC_ID }}"
          
        ${HOME}/run-test.sh \
          "${{ secrets.GITHUB_TOKEN }}" \
          "${{ github.repository }}" \
          "${{ env.LAC_ID }}" \
          "${{ env.TEST_ID }}" \
          "${{ vars.PERFORMANCE_HOME }}" \
          "${{ github.actor }}" \
          "${{ github.ref_name }}" \
          "${{ secrets.VAULT_TOKEN }}"

        if [ $? -ne 0 ]; then
          echo "Performance test failed"
          exit 1
        fi

    - name: Cleanup remote job
      if: ${{ always() }}
      run: |
        ${HOME}/cleanup-remote-job.sh \
          "${{ env.LAC_ID }}" \
          "${{ env.TEST_ID }}" \
          "${{ secrets.VAULT_TOKEN }}"