name: LAC.0001-TEST.0001-Load-Test-standalone

on:
  workflow_dispatch

jobs:
  performance-test:
    runs-on: self-hosted
    timeout-minutes: 60  # Set timeout to 60 minutes (1 hour)
    steps:
    - name: Defining test specific environment variables
      run: |

        # Test specific environment variables
        echo "LAC_ID=LAC.0001" >> $GITHUB_ENV
        echo "TEST_ID=TEST.0001" >> $GITHUB_ENV
        SECRET_VALUE="${{ secrets.LAC0001_TEST0001 }}"
        
        # Test if secrets.<LAC_ID>_<TEST_ID> exists and is valid JSON
        
        if [ -n "$SECRET_VALUE" ]; then
          ENCODED_SECRET=$(echo "$SECRET_VALUE" | base64 -w 0)
          echo "AUTHENTICATION=$ENCODED_SECRET" >> $GITHUB_ENV
        fi

    - name: Running test  
      run: |
        echo "Running performance test ${{ env.TEST_ID }} on LAC ${{ env.LAC_ID }}"
        
        ${HOME}/run-test.sh \
          "${{ secrets.GITHUB_TOKEN }}" \
          "${{ github.repository }}" \
          "${{ env.LAC_ID }}" \
          "${{ env.TEST_ID }}" \
          "${{ vars.PERFORMANCE_HOME }}" \
          "${{ github.actor }}" \
          "${{ github.ref_name }}" \
          "${{ secrets.VAULT_TOKEN }}" \
          "${{ env.AUTHENTICATION }}"

        if [ $? -ne 0 ]; then
          echo "Performance test failed"
          exit 1
        fi

    - name: Cleanup remote job
      if: ${{ always() }}
      run: |
        ${HOME}/cleanup-remote-job.sh \
          "${{ env.LAC_ID }}" \
          "${{ env.TEST_ID }}" \
          "${{ secrets.VAULT_TOKEN }}"